##
# Schema summary:
#
# uri_*_txt          arbitrary RDF objects
# kq_meta_*          normalized metadata schema into which many of the
#                    uri_* fields are copied (notably, /dc/elements/1.1 and
#                    /dc/terms are merged)
# kq_meta_title_s    Single-valued title field that can be sorted (must be
#                    populated manually)
# kq_meta_date_dts   Single-valued date field
# kq_sys_*           system properties
# kq_*_facet         facets
# kq_searchall_txt   full-text search field
#
# There are no classic fields, only dynamicFields and copyFields.
#
copyFields: # TODO: replace these with a "normalized fields" feature
  # Map various fields to Kumquat's own schema. The main purpose
  # of this is to normalize the DC elements and terms.
  - source: uri_http_purl_org_dc_elements_1_1_contributor_txt
    dest: kq_meta_contributor_txt
  - source: uri_http_purl_org_dc_elements_1_1_coverage_txt
    dest: kq_meta_coverage_txt
  - source: uri_http_purl_org_dc_elements_1_1_creator_txt
    dest: kq_meta_creator_txt
  - source: uri_http_purl_org_dc_elements_1_1_date_txt
    dest: kq_meta_date_txt
  - source: uri_http_purl_org_dc_elements_1_1_description_txt
    dest: kq_meta_description_txt
  - source: uri_http_purl_org_dc_elements_1_1_format_txt
    dest: kq_meta_format_txt
  - source: uri_http_purl_org_dc_elements_1_1_identifier_s
    dest: kq_meta_identifier_txt
  - source: uri_http_purl_org_dc_elements_1_1_language_txt
    dest: kq_meta_language_txt
  - source: uri_http_purl_org_dc_elements_1_1_publisher_txt
    dest: kq_meta_publisher_txt
  - source: uri_http_purl_org_dc_elements_1_1_relation_txt
    dest: kq_meta_relation_txt
  - source: uri_http_purl_org_dc_elements_1_1_rights_txt
    dest: kq_meta_rights_txt
  - source: uri_http_purl_org_dc_elements_1_1_source_txt
    dest: kq_meta_source_txt
  - source: uri_http_purl_org_dc_elements_1_1_subject_txt
    dest: kq_meta_subject_txt
  - source: uri_http_purl_org_dc_elements_1_1_title_txt
    dest: kq_meta_title_txt
  - source: uri_http_purl_org_dc_elements_1_1_type_txt
    dest: kq_meta_type_txt
  - source: uri_http_purl_org_dc_terms_abstract_txt
    dest: kq_meta_abstract_txt
  - source: uri_http_purl_org_dc_terms_accessRights_txt
    dest: kq_meta_accessRights_txt
  - source: uri_http_purl_org_dc_terms_accrualMethod_txt
    dest: kq_meta_accrualMethod_txt
  - source: uri_http_purl_org_dc_terms_accrualPeriodicity_txt
    dest: kq_meta_accrualPeriodicity_txt
  - source: uri_http_purl_org_dc_terms_accrualPolicy_txt
    dest: kq_meta_accrualPolicy_txt
  - source: uri_http_purl_org_dc_terms_alternative_txt
    dest: kq_meta_alternative_txt
  - source: uri_http_purl_org_dc_terms_audience_txt
    dest: kq_meta_audience_txt
  - source: uri_http_purl_org_dc_terms_available_txt
    dest: kq_meta_available_txt
  - source: uri_http_purl_org_dc_terms_bibliographicCitation_txt
    dest: kq_meta_bibliographicCitation_txt
  - source: uri_http_purl_org_dc_terms_conformsTo_txt
    dest: kq_meta_conformsTo_txt
  - source: uri_http_purl_org_dc_terms_contributor_txt
    dest: kq_meta_contributor_txt
  - source: uri_http_purl_org_dc_terms_coverage_txt
    dest: kq_meta_coverage_txt
  - source: uri_http_purl_org_dc_terms_created_txt
    dest: kq_meta_created_txt
  - source: uri_http_purl_org_dc_terms_creator_txt
    dest: kq_meta_creator_txt
  - source: uri_http_purl_org_dc_terms_date_txt
    dest: kq_meta_date_txt
  - source: uri_http_purl_org_dc_terms_dateAccepted_txt
    dest: kq_meta_dateAccepted_txt
  - source: uri_http_purl_org_dc_terms_dateCopyrighted_txt
    dest: kq_meta_dateCopyrighted_txt
  - source: uri_http_purl_org_dc_terms_dateSubmitted_txt
    dest: kq_meta_dateSubmitted_txt
  - source: uri_http_purl_org_dc_terms_description_txt
    dest: kq_meta_description_txt
  - source: uri_http_purl_org_dc_terms_educationLevel_txt
    dest: kq_meta_educationLevel_txt
  - source: uri_http_purl_org_dc_terms_extent_txt
    dest: kq_meta_extent_txt
  - source: uri_http_purl_org_dc_terms_format_txt
    dest: kq_meta_format_txt
  - source: uri_http_purl_org_dc_terms_hasFormat_txt
    dest: kq_meta_hasFormat_txt
  - source: uri_http_purl_org_dc_terms_hasPart_txt
    dest: kq_meta_hasPart_txt
  - source: uri_http_purl_org_dc_terms_hasVersion_txt
    dest: kq_meta_hasVersion_txt
  - source: uri_http_purl_org_dc_terms_identifier_txt
    dest: kq_meta_identifier_txt
  - source: uri_http_purl_org_dc_terms_instructionalMethod_txt
    dest: kq_meta_instructionalMethod_txt
  - source: uri_http_purl_org_dc_terms_isFormatOf_txt
    dest: kq_meta_isFormatOf_txt
  - source: uri_http_purl_org_dc_terms_isPartOf_txt
    dest: kq_meta_isPartOf_txt
  - source: uri_http_purl_org_dc_terms_isReferencedBy_txt
    dest: kq_meta_isReferencedBy_txt
  - source: uri_http_purl_org_dc_terms_isReplacedBy_txt
    dest: kq_meta_isReplacedBy_txt
  - source: uri_http_purl_org_dc_terms_isRequiredBy_txt
    dest: kq_meta_isRequiredBy_txt
  - source: uri_http_purl_org_dc_terms_issued_txt
    dest: kq_meta_issued_txt
  - source: uri_http_purl_org_dc_terms_isVersionOf_txt
    dest: kq_meta_language_txt
  - source: uri_http_purl_org_dc_terms_language_txt
    dest: kq_meta_language_txt
  - source: uri_http_purl_org_dc_terms_license_txt
    dest: kq_meta_license_txt
  - source: uri_http_purl_org_dc_terms_mediator_txt
    dest: kq_meta_mediator_txt
  - source: uri_http_purl_org_dc_terms_medium_txt
    dest: kq_meta_medium_txt
  - source: uri_http_purl_org_dc_terms_modified_txt
    dest: kq_meta_modified_txt
  - source: uri_http_purl_org_dc_terms_provenance_txt
    dest: kq_meta_provenance_txt
  - source: uri_http_purl_org_dc_terms_publisher_txt
    dest: kq_meta_publisher_txt
  - source: uri_http_purl_org_dc_terms_references_txt
    dest: kq_meta_references_txt
  - source: uri_http_purl_org_dc_terms_relation_txt
    dest: kq_meta_relation_txt
  - source: uri_http_purl_org_dc_terms_replaces_txt
    dest: kq_meta_replaces_txt
  - source: uri_http_purl_org_dc_terms_requires_txt
    dest: kq_meta_requires_txt
  - source: uri_http_purl_org_dc_terms_rights_txt
    dest: kq_meta_rights_txt
  - source: uri_http_purl_org_dc_terms_rightsHolder_txt
    dest: kq_meta_rightsHolder_txt
  - source: uri_http_purl_org_dc_terms_source_txt
    dest: kq_meta_source_txt
  - source: uri_http_purl_org_dc_terms_spatial_txt
    dest: kq_meta_spatial_txt
  - source: uri_http_purl_org_dc_terms_subject_txt
    dest: kq_meta_subject_txt
  - source: uri_http_purl_org_dc_terms_tableOfContents_txt
    dest: kq_meta_tableOfContents_txt
  - source: uri_http_purl_org_dc_terms_temporal_txt
    dest: kq_meta_temporal_txt
  - source: uri_http_purl_org_dc_terms_title_txt
    dest: kq_meta_title_txt
  - source: uri_http_purl_org_dc_terms_type_txt
    dest: kq_meta_type_txt
  - source: uri_http_purl_org_dc_terms_valid_txt
    dest: kq_meta_valid_txt
dynamicFields:
  - name: '*_facet'
    type: string
    stored: true
    indexed: true
    multiValued: true
    docValues: true
  - name: '*_i'
    type: int
    stored: true
    indexed: true
  - name: '*_is'
    type: int
    stored: true
    indexed: true
    multiValued: true
  - name: '*_s'
    type: string
    stored: true
    indexed: true
  - name: '*_ss'
    type: string
    stored: true
    indexed: true
    multiValued: true
  - name: '*_l'
    type: long
    stored: true
    indexed: true
  - name: '*_ls'
    type: long
    stored: true
    indexed: true
    multiValued: true
  - name: '*_t'
    type: text_general
    stored: true
    indexed: true
  - name: '*_txt'
    type: text_general
    stored: true
    indexed: true
    multiValued: true
  - name: '*_en'
    type: text_en
    stored: true
    indexed: true
    multiValued: true
  - name: '*_b'
    type: boolean
    stored: true
    indexed: true
  - name: '*_bs'
    type: boolean
    stored: true
    indexed: true
    multiValued: true
  - name: '*_f'
    type: float
    stored: true
    indexed: true
  - name: '*_fs'
    type: float
    stored: true
    indexed: true
    multiValued: true
  - name: '*_d'
    type: double
    stored: true
    indexed: true
  - name: '*_ds'
    type: double
    stored: true
    multiValued: true
  # Type used to index the lat and lon components for the "location" FieldType
  - name: '*_coordinate'
    type: tdouble
    indexed: true
    stored: false
  - name: '*_dt'
    type: date
    indexed: true
    stored: true
  - name: '*_dts'
    type: date
    indexed: false
    stored: true
  - name: '*_dtsi'
    type: date
    indexed: true
    stored: true
  - name: '*_dtsim'
    type: date
    indexed: true
    stored: true
    multiValued: true
  - name: '*_p'
    type: location
    indexed: true
    stored: true
  # some trie-coded dynamic fields for faster range queries
  - name: '*_ti'
    type: tint
    indexed: true
    stored: true
  - name: '*_tl'
    type: tlong
    indexed: true
    stored: true
  - name: '*_tf'
    type: tfloat
    indexed: true
    stored: true
  - name: '*_td'
    type: tdouble
    indexed: true
    stored: true
  - name: '*_tdt'
    type: tdate
    indexed: true
    stored: true
  - name: '*_c'
    type: currency
    indexed: true
    stored: true
  - name: 'ignored_*'
    type: ignored
    multiValued: true
  - name: 'attr_*'
    type: text_general
    indexed: true
    stored: true
    multiValued: true
  - name: 'random_*'
    type: random
  - name: '*_facet'
    type: string
    docValues: true
    multiValued: true
    indexed: true
    stored: true
